python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_n_y_Cons_0_cons_BD_UGAMr_BL_MC3noMix.trees.tree y
python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_n_y_Cons_1_cons_BD_UGAMr_BL_MC3noMix.trees.tree y
python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_n_y_Cons_5_cons_BD_UGAMr_BL_MC3noMix.trees.tree y
python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_n_y_Cons_10_cons_BD_UGAMr_BL_MC3noMix.trees.tree y
python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_n_y_Cons_15_cons_BD_UGAMr_BL_MC3noMix.trees.tree y

python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_y_y_Cons_0_cons_BD_UGAMr_BL_MC3noMix.trees.tree y
python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_y_y_Cons_1_cons_BD_UGAMr_BL_MC3noMix.trees.tree y
python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_y_y_Cons_5_cons_BD_UGAMr_BL_MC3noMix.trees.tree y
python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_y_y_Cons_15_cons_BD_UGAMr_BL_MC3noMix.trees.tree y



####python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_y_y_Cons_15_cons_BD_WNr_BL.tree
