python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_n_y_Cons_0_BD_WNr_BL.tree
python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_n_y_Cons_1_cons_BD_WNr_BL.tree
python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_n_y_Cons_5_cons_BD_WNr_BL.tree
python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_n_y_Cons_10_cons_BD_WNr_BL.tree
python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_n_y_Cons_15_cons_BD_WNr_BL.tree

python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_y_y_Cons_0_BD_WNr_BL.tree
python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_y_y_Cons_1_cons_BD_WNr_BL.tree
python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_y_y_Cons_5_cons_BD_WNr_BL.tree
python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_y_y_Cons_10_cons_BD_WNr_BL.tree
python Scripts/analyzeMAPTree.py SimulatedTrees/proposedTree.dnd OutputDating/Cal_10_y_y_Cons_15_cons_BD_WNr_BL.tree
